apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-python-container
  labels:
    app: my-python-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-python-app
  template:
    metadata:
      labels:
        app: my-python-app
    spec:
      containers:
      - name: my-python-container
        image: shimamsa/my-python-container:latest
        ports:
        - containerPort: 8000
